# Generated by Django 4.2.14 on 2024-08-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='pos',
            new_name='post',
        ),
    ]
